# Generated by Django 5.2.8 on 2025-12-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_add_author_and_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritearticle',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='收藏时间'),
        ),
    ]
