# Generated by Django 5.1 on 2025-07-23 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'View statistics',
                'verbose_name_plural': 'View statistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'date'], name='user_views_content_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='user_views_content_type_idx')],
            },
        ),
    ]
