# Generated by Django 5.1.6 on 2025-03-11 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add time')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('sort', models.IntegerField(default=0, verbose_name='sort')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'ordering': ['-sort'],
            },
        ),
    ]
