# Generated by Django 5.2.5 on 2025-09-17 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Pet Name')),
                ('species', models.CharField(max_length=40, verbose_name='Species')),
                ('breed', models.CharField(blank=True, default='', max_length=80, verbose_name='Breed')),
                ('sex', models.CharField(blank=True, default='', max_length=10, verbose_name='Sex')),
                ('age_months', models.PositiveIntegerField(default=0, verbose_name='Age (months)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('location', models.CharField(blank=True, default='', max_length=120, verbose_name='Location')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Cover')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted'), ('archived', 'Archived')], db_index=True, default='available', max_length=20, verbose_name='Status')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-pub_date'],
                'indexes': [models.Index(fields=['status'], name='pet_pet_status_d405f9_idx'), models.Index(fields=['species', 'breed'], name='pet_pet_species_aeab59_idx'), models.Index(fields=['created_by'], name='pet_pet_created_66a81e_idx')],
            },
        ),
    ]
