# Generated by Django 5.2.5 on 2025-09-18 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_age_years_alter_pet_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message to Owner')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=20, verbose_name='Status')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_adoption', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pet.pet')),
            ],
            options={
                'verbose_name': 'Adoption',
                'verbose_name_plural': 'Adoption',
                'ordering': ['-pub_date'],
                'indexes': [models.Index(fields=['pet', 'status'], name='pet_adoptio_pet_id_3c28ca_idx'), models.Index(fields=['applicant', 'status'], name='pet_adoptio_applica_ca5b73_idx')],
            },
        ),
    ]
