# Generated by Django 5.2.5 on 2025-09-20 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_adoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Pet Name')),
                ('species', models.CharField(max_length=40, verbose_name='Species')),
                ('breed', models.CharField(blank=True, default='', max_length=80, verbose_name='Breed')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Sex')),
                ('age_years', models.PositiveIntegerField(default=0, verbose_name='Age (years)')),
                ('age_months', models.PositiveIntegerField(default=0, verbose_name='Age (months)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('location', models.CharField(blank=True, default='', max_length=120, verbose_name='Location')),
                ('dewormed', models.BooleanField(default=False, verbose_name='Dewormed')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Vaccinated')),
                ('microchipped', models.BooleanField(default=False, verbose_name='Microchipped')),
                ('is_stray', models.BooleanField(default=False, verbose_name='Found as Stray')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Phone')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20, verbose_name='Status')),
                ('review_note', models.CharField(blank=True, default='', max_length=200, verbose_name='Review Note')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_pet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_donor', to='pet.pet')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_donor', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='DonationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donations/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pet.donation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='pet_donatio_status_533559_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor'], name='pet_donatio_donor_i_9c757c_idx'),
        ),
    ]
