# Generated by Django 5.2.5 on 2025-09-20 18:21

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_donation_donationphoto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoption',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Adoption', 'verbose_name_plural': 'Adoptions'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Poland', max_length=64, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='', max_length=64, verbose_name='City')),
                ('district', models.CharField(blank=True, default='', max_length=64, verbose_name='District')),
                ('street', models.CharField(blank=True, default='', max_length=128, verbose_name='Street')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Lat')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Lng')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'indexes': [models.Index(fields=['country', 'city'], name='pet_address_country_d767bd_idx'), models.Index(fields=['postal_code'], name='pet_address_postal__555dd9_idx')],
                'constraints': [models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('country', 'city', 'district', 'street', 'postal_code', 'latitude', 'longitude'), name='uniq_full_address')],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='pet.address'),
        ),
        migrations.AddField(
            model_name='pet',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pet.address'),
        ),
    ]
