# Generated by Django 5.2.5 on 2025-09-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_city_country_region_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['country', 'region', 'city', 'street'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country', 'region', 'city'], name='pet_address_country_8537a3_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code'], name='pet_address_postal__555dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['region', 'name'], name='pet_city_region__73d7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['country', 'name'], name='pet_region_country_384b1b_idx'),
        ),
    ]
