# Generated by Django 5.2.5 on 2025-09-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='building_number',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Building No.'),
        ),
    ]
