# Generated by Django 5.2.5 on 2025-09-21 18:16

import apps.pet.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_address_building_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(help_text='cat/dog/…', max_length=50)),
                ('breed', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('sex', models.CharField(blank=True, default='', max_length=10)),
                ('size', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('lost_time', models.DateTimeField(help_text='Lost time (local)')),
                ('description', models.TextField(blank=True, default='')),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.pet.models.lost_upload_to)),
                ('status', models.CharField(choices=[('open', 'Open'), ('found', 'Found'), ('closed', 'Closed')], default='open', max_length=20)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.country')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_reports', to='pet.pet')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.region')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost',
                'verbose_name_plural': 'Losts',
                'ordering': ['-created_at'],
            },
        ),
    ]
