# Generated by Django 5.2.5 on 2025-09-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_remove_lost_pet_lost_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Sex'),
        ),
    ]
