# Generated by Django 5.2.5 on 2025-09-21 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_alter_lost_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_reports', to='pet.pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted'), ('archived', 'Archived'), ('lost', 'Lost')], db_index=True, default='available', max_length=20, verbose_name='Status'),
        ),
    ]
