# Generated by Django 5.2.7 on 2025-10-16 22:34

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0014_lost_pet_alter_pet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='idx_address_location_gist'),
        ),
    ]
