# Generated by Django 5.2.8 on 2025-11-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0016_location_donation_location_pet_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='location',
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/photos/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pet.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Pet Photo',
                'verbose_name_plural': 'Pet Photos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
