# Generated by Django 5.2.8 on 2025-12-03 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0017_remove_donation_location_remove_pet_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='pet.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Favorite',
                'verbose_name_plural': 'Pet Favorites',
                'indexes': [models.Index(fields=['user', 'pet'], name='pet_petfavo_user_id_cbfb3c_idx')],
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
