# Generated by Django 5.2.8 on 2025-12-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0018_petfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='affectionate',
            field=models.BooleanField(default=False, verbose_name='Affectionate'),
        ),
        migrations.AddField(
            model_name='pet',
            name='child_friendly',
            field=models.BooleanField(default=False, verbose_name='Child Friendly'),
        ),
        migrations.AddField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='pet',
            name='dewormed',
            field=models.BooleanField(default=False, verbose_name='Dewormed'),
        ),
        migrations.AddField(
            model_name='pet',
            name='good_with_cats',
            field=models.BooleanField(default=False, verbose_name='Good with Cats'),
        ),
        migrations.AddField(
            model_name='pet',
            name='good_with_dogs',
            field=models.BooleanField(default=False, verbose_name='Good with Dogs'),
        ),
        migrations.AddField(
            model_name='pet',
            name='loves_play',
            field=models.BooleanField(default=False, verbose_name='Loves to Play'),
        ),
        migrations.AddField(
            model_name='pet',
            name='loves_walks',
            field=models.BooleanField(default=False, verbose_name='Loves Walks'),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchipped',
            field=models.BooleanField(default=False, verbose_name='Microchipped'),
        ),
        migrations.AddField(
            model_name='pet',
            name='needs_attention',
            field=models.BooleanField(default=False, verbose_name='Needs Attention'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sterilized',
            field=models.BooleanField(default=False, verbose_name='Sterilized/Neutered'),
        ),
        migrations.AddField(
            model_name='pet',
            name='trained',
            field=models.BooleanField(default=False, verbose_name='House Trained'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccinated',
            field=models.BooleanField(default=False, verbose_name='Vaccinated'),
        ),
    ]
