# Generated by Django 5.2.8 on 2025-12-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0019_pet_affectionate_pet_child_friendly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='affectionate',
            field=models.BooleanField(default=False, verbose_name='Affectionate'),
        ),
        migrations.AddField(
            model_name='donation',
            name='child_friendly',
            field=models.BooleanField(default=False, verbose_name='Child Friendly'),
        ),
        migrations.AddField(
            model_name='donation',
            name='good_with_cats',
            field=models.BooleanField(default=False, verbose_name='Good with Cats'),
        ),
        migrations.AddField(
            model_name='donation',
            name='good_with_dogs',
            field=models.BooleanField(default=False, verbose_name='Good with Dogs'),
        ),
        migrations.AddField(
            model_name='donation',
            name='loves_play',
            field=models.BooleanField(default=False, verbose_name='Loves to Play'),
        ),
        migrations.AddField(
            model_name='donation',
            name='loves_walks',
            field=models.BooleanField(default=False, verbose_name='Loves Walks'),
        ),
        migrations.AddField(
            model_name='donation',
            name='needs_attention',
            field=models.BooleanField(default=False, verbose_name='Needs Attention'),
        ),
        migrations.AddField(
            model_name='donation',
            name='sterilized',
            field=models.BooleanField(default=False, verbose_name='Sterilized/Neutered'),
        ),
        migrations.AddField(
            model_name='donation',
            name='trained',
            field=models.BooleanField(default=False, verbose_name='House Trained'),
        ),
    ]
