# Generated by Django 5.2.8 on 2025-12-15 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0020_donation_affectionate_donation_child_friendly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Shelter Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shelters/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='shelters/covers/', verbose_name='Cover Image')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Maximum number of animals', verbose_name='Capacity')),
                ('current_animals', models.PositiveIntegerField(default=0, verbose_name='Current Animals')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Founded Year')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin', verbose_name='Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='Twitter/X')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelters', to='pet.address', verbose_name='Address')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shelters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Shelter',
                'verbose_name_plural': 'Shelters',
                'ordering': ['-is_verified', 'name'],
                'indexes': [models.Index(fields=['is_active', 'is_verified'], name='pet_shelter_is_acti_7f7b3c_idx'), models.Index(fields=['name'], name='pet_shelter_name_0e4218_idx')],
            },
        ),
    ]
