# Generated by Django 5.2.5 on 2025-09-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Age (years)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Sex'),
        ),
    ]
