# Generated by Django 5.2.5 on 2025-09-21 18:34

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.PROTECT, to='pet.region'),
        ),
    ]
