# Generated by Django 5.2.5 on 2025-09-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_alter_lost_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='country',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='region',
        ),
        migrations.AlterField(
            model_name='lost',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losts', to='pet.address', verbose_name='Address'),
        ),
    ]
