# Generated by Django 5.2.5 on 2025-09-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_remove_lost_city_remove_lost_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='pet',
        ),
        migrations.AddField(
            model_name='lost',
            name='pet_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Pet Name'),
        ),
    ]
