# Generated by Django 5.1 on 2025-07-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='viewstatistics',
            name='user_views_content_type_idx',
        ),
        migrations.AddConstraint(
            model_name='viewstatistics',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'date'), name='user_views_content_type_idx'),
        ),
    ]
