# Generated by Django 5.2.8 on 2025-12-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='其他偏好说明'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_experience',
            field=models.BooleanField(default=False, help_text='是否有养宠经验'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_yard',
            field=models.BooleanField(default=False, help_text='是否有院子'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='living_situation',
            field=models.CharField(blank=True, help_text='居住环境（如：apartment, house）', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_pets',
            field=models.CharField(blank=True, help_text='家中其他宠物', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_age_max',
            field=models.IntegerField(blank=True, help_text='偏好的最大年龄（月）', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_age_min',
            field=models.IntegerField(blank=True, help_text='偏好的最小年龄（月）', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_gender',
            field=models.CharField(blank=True, help_text='偏好的性别（male/female）', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_size',
            field=models.CharField(blank=True, help_text='偏好的大小（如：small, medium, large）', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_species',
            field=models.CharField(blank=True, help_text='偏好的物种（如：dog, cat）', max_length=50),
        ),
    ]
