# Generated by Django 5.2.8 on 2025-12-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='user_notifi_user_id_7c7879_idx',
            old_name='user_notification_user_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='user_notifi_user_id_c3061c_idx',
            old_name='user_notification_user_id_is_read_idx',
        ),
    ]
