# Generated by Django 5.2.9 on 2025-12-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User avatar image', null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
