# Generated by Django 5.2.9 on 2025-12-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_friendship_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prefer_affectionate',
            field=models.BooleanField(default=False, help_text='偏好富有感情的宠物'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_child_friendly',
            field=models.BooleanField(default=False, help_text='偏好适合儿童的宠物'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_dewormed',
            field=models.BooleanField(default=False, help_text='偏好已驱虫的宠物'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_good_with_cats',
            field=models.BooleanField(default=False, help_text='偏好与猫相处友善的宠物'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_good_with_dogs',
            field=models.BooleanField(default=False, help_text='偏好与其他狗相处友善的宠物'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_loves_play',
            field=models.BooleanField(default=False, help_text='偏好喜欢玩耍的宠物'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_loves_walks',
            field=models.BooleanField(default=False, help_text='偏好喜欢散步的宠物'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_needs_attention',
            field=models.BooleanField(default=False, help_text='偏好需要陪伴的宠物'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_sterilized',
            field=models.BooleanField(default=False, help_text='偏好已绝育的宠物'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_trained',
            field=models.BooleanField(default=False, help_text='偏好已训练的宠物'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_vaccinated',
            field=models.BooleanField(default=False, help_text='偏好已接种疫苗的宠物'),
        ),
    ]
